M48
; DRILL file {KiCad 7.0.1} date Sun Apr 16 19:55:21 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-16T19:55:21+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X89.535Y-62.23
X89.535Y-119.38
X170.815Y-62.23
X170.815Y-119.38
T0
M30
